### ISSUE TITLE
Distribute builds of RPM package

### ISSUE THREAD

**Issue by jkonecny12** [leonmaxx/primus-vk-rpm#1]
Hello, 

Thanks for this RPM package. Don't you want to also create builds for distributions? It would be easier to just add a repository and install the package.

You can use for this Fedora COPR build system. This also creates packages for OpenSuse and Mageia if set.

https://copr.fedorainfracloud.org

**Comment by leonmaxx** [comment]
Hello,

Thanks for suggestion. I just tested creating packages on COPR, scripts needs some modifications to build automatically. Need some free time to do it properly.

Some of builds are already available: [primus-vk COPR](https://copr.fedorainfracloud.org/coprs/leonmaxx/primus-vk-rpm/)

**Comment by jkonecny12** [comment]
I'm using this solution for daily builds if you are interested.
https://github.com/vojtechtrefny/copr-builder

Thanks for the first builds!
