### ISSUE TITLE
Can't compile on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by KhazAkar** [leonmaxx/primus-vk-rpm#5]
Hi! I cannot compile primus_vk using your repo, that's the problem:
`Downloading...
Building 64-bit package...
error: Failed build dependencies:
	mesa-libGL-devel is needed by primus-vk-20190306-1.x86_64
Building 32-bit package...
Building target platforms: i686
Building for target i686
error: Failed build dependencies:
	mesa-libGL-devel is needed by primus-vk-20190306-1.i686
`
But... I can compile code from primus_vk repo directly, just cannot package that.

**Comment by leonmaxx** [comment]
Hello. Mesa packages on Fedora/CentOS and OpenSUSE have different names.  
Try:  
```
sed -i 's/mesa-libGL-devel/Mesa-libGL-devel/g' primus-vk.spec
./create-package.sh
```

**Comment by KhazAkar** [comment]
Thanks, but still don't want to work, here's the error:
`Downloading...
Building 64-bit package...
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.imyw7c
+ umask 022
+ cd /home/khazakar/softzgh/primus-vk-rpm/work/BUILD
+ cd /home/khazakar/softzgh/primus-vk-rpm/work/BUILD
+ rm -rf primus_vk-master
+ /usr/bin/unzip -qq /home/khazakar/softzgh/primus-vk-rpm/work/SOURCES/primus_vk-master.zip
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd primus_vk-master
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ echo 'Patch #0 (makefile.patch):'
Patch #0 (makefile.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
patching file Makefile
Hunk #1 FAILED at 1.
Hunk #2 FAILED at 9.
2 out of 2 hunks FAILED -- saving rejects to file Makefile.rej
error: Bad exit status from /var/tmp/rpm-tmp.imyw7c (%prep)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.imyw7c (%prep)
Building 32-bit package...
Building target platforms: i686
Building for target i686
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.uuKhde
+ umask 022
+ cd /home/khazakar/softzgh/primus-vk-rpm/work/BUILD
+ cd /home/khazakar/softzgh/primus-vk-rpm/work/BUILD
+ rm -rf primus_vk-master
+ /usr/bin/unzip -qq /home/khazakar/softzgh/primus-vk-rpm/work/SOURCES/primus_vk-master.zip
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd primus_vk-master
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ echo 'Patch #0 (makefile.patch):'
Patch #0 (makefile.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
patching file Makefile
Hunk #1 FAILED at 1.
Hunk #2 FAILED at 9.
2 out of 2 hunks FAILED -- saving rejects to file Makefile.rej
error: Bad exit status from /var/tmp/rpm-tmp.uuKhde (%prep)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.uuKhde (%prep)`

**Comment by leonmaxx** [comment]
I just pushed updated version, can you pull latest changes or re-download source archive and try again?
*Do not forget to fix Mesa-libGL-devel dependency with `sed` command i posted above*

**Comment by leonmaxx** [comment]
Also, I cannot guarantee that it will work on OpenSUSE even if it builds and installs normally.

**Comment by KhazAkar** [comment]
Next problem, with missing crash-fix.patch
`/create-package.sh 
Downloading...
Building 64-bit package...
error: Bad source: /home/khazakar/softzgh/primus-vk-rpm/work/SOURCES/crash-fix.patch: No such file or directory
Building 32-bit package...
Building target platforms: i686
Building for target i686
error: Bad source: /home/khazakar/softzgh/primus-vk-rpm/work/SOURCES/crash-fix.patch: No such file or directory
`

**Comment by leonmaxx** [comment]
Sorry, missed that file. Please pull again.

**Comment by KhazAkar** [comment]
Em... doesn't compile, missing gnu/stubs-32.h
https://pastebin.com/kGJuccqn

**Comment by leonmaxx** [comment]
```
Wrote: /home/khazakar/softzgh/primus-vk-rpm/RPMs/src/primus-vk-20190306-3.src.rpm
Wrote: /home/khazakar/softzgh/primus-vk-rpm/RPMs/x86_64/primus-vk-20190306-3.x86_64.rpm
Wrote: /home/khazakar/softzgh/primus-vk-rpm/RPMs/x86_64/primus-vk-libs-20190306-3.x86_64.rpm
```
64-bit packages are built ok, now you need to install gcc/glibc 32-bit development files to build also 32-bit packages.

**Comment by leonmaxx** [comment]
Possibly it's `glibc-devel.i686` package.

**Comment by KhazAkar** [comment]
32 bit still don't want to build, because it points to 64 bit compiler, not 32 bit one. I've installed it and needed ld binary is in /usr/i586-suse-linux/bin folder.

**Comment by leonmaxx** [comment]
It can be build with 64-bit compiler and linker but with "-m32" option, if it doesn't then some package is still missing. Try `glibc-devel-32bit` package.

**Comment by KhazAkar** [comment]
I have it installed and still don't want to build :/

**Comment by leonmaxx** [comment]
Is `gcc-32bit` installed?

**Comment by leonmaxx** [comment]
We need OpenSUSE packaging expert here.

**Comment by leonmaxx** [comment]
As I do not plan to support OpenSUSE, and reporter seems to lost interest - closing.
