### ISSUE TITLE
Failed to Synchronize cache for 'leonmaxx-primus'

### ISSUE THREAD

**Issue by Tetrastorm** [leonmaxx/primus-vk-rpm#6]
I **failed to install primus-vk** with the command: `sudo dnf install primus-vk primus-vk-libs.i686`

I've in **output**:
```
Copr repo for primus-vk-rpm owned by leonmaxx
Failed to synchronize cache for repo 'leonmaxx-primus-vk-rpm'
...
Ignoring repositories: leonmaxx-primus-vk-rpm
No match for argument: primus-vk
No match for argument: primus-vk-libs.i686
Error: Unable to find a match
```

**Os:** Fedora 30
**Copr with:** `sudo dnf copr enable leonmaxx/primus-vk-rpm`

**Note:**
I'm install bumblebee owned by chenxiaolong in my computer.

**Comment by leonmaxx** [comment]
Hello, I just regenerated repositories on copr. Please, clear dnf cache `dnf clean all` and try again.

**Comment by leonmaxx** [comment]
Also, have you read installation instructions?
https://copr.fedorainfracloud.org/coprs/leonmaxx/primus-vk-rpm/

**Comment by Tetrastorm** [comment]
I've retry, this don't work again. I've too forgotten to change the .repo, but even after the change, the install failed with the same error than before.

**Comment by afraidofmusic** [comment]
In https://copr-be.cloud.fedoraproject.org/results/leonmaxx/primus-vk-rpm/ I can't see fedora-30-x86_64 or fedora-30-i386 folders which dnf would look for, I think?

**Comment by leonmaxx** [comment]
Fresh build is [on COPR](https://copr.fedorainfracloud.org/coprs/leonmaxx/primus-vk-rpm/) with updated `primus_vk` sources to v1.0, F30 is enabled.

**Comment by leonmaxx** [comment]
Package sources is out of sync, will commit changes later.
